export const data=[{"id":1,"content":"Database Administrator III"},
{"id":2,"content":"Assistant Manager"},
{"id":3,"content":"Dental Hygienist"},
{"id":4,"content":"Web Designer IV"},
{"id":5,"content":"Dental Hygienist"},
{"id":6,"content":"Librarian"},
{"id":7,"content":"Chief Design Engineer"},
{"id":8,"content":"Speech Pathologist"},
{"id":9,"content":"Cost Accountant"},
{"id":10,"content":"Help Desk Operator"},
{"id":11,"content":"Help Desk Operator"},
{"id":12,"content":"Safety Technician I"},
{"id":13,"content":"Sales Associate"},
{"id":14,"content":"Registered Nurse"},
{"id":15,"content":"Director of Sales"},
{"id":16,"content":"Sales Associate"},
{"id":17,"content":"Geologist II"},
{"id":18,"content":"Associate Professor"},
{"id":19,"content":"Human Resources Manager"},
{"id":20,"content":"GIS Technical Architect"}]